#!/usr/bin/env python
"""Build the documentation site served at docs/ by GitHub Pages.

Run from the repository root::

    python tools/build_docs.py

Everything the site states about the package is read from the package itself:
the API reference is generated by importing ``embedresearchgaps`` and reading
signatures and docstrings, and the guide is rendered from ``README.md``. Nothing
is written by hand twice, so the site cannot drift from the code the way a
hand-maintained copy would -- rebuild it whenever the public API changes.

Standard library only, by design: a documentation build that needs its own
dependency tree is a documentation build that stops working.
"""

from __future__ import annotations

import dataclasses
import html
import importlib
import inspect
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "docs"

sys.path.insert(0, str(SRC))

REPO_URL = "https://github.com/s-matysik/EmbedResearchGaps"

# --------------------------------------------------------------------------
# A markdown subset: headings, fenced code, tables, lists, quotes, inline spans.
# --------------------------------------------------------------------------

_INLINE_CODE = re.compile(r"`([^`]+)`")
_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_ITALIC = re.compile(r"(?<![\w*])\*([^*\n]+)\*(?![\w*])")
_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


def inline(text: str) -> str:
    """Escape, then re-introduce the inline spans markdown defines."""
    out = html.escape(text, quote=False)
    placeholders: list[str] = []

    def stash(match: re.Match[str]) -> str:
        placeholders.append(f"<code>{match.group(1)}</code>")
        return f"\x00{len(placeholders) - 1}\x00"

    out = _INLINE_CODE.sub(stash, out)
    out = _LINK.sub(r'<a href="\2">\1</a>', out)
    out = _BOLD.sub(r"<strong>\1</strong>", out)
    out = _ITALIC.sub(r"<em>\1</em>", out)
    for index, value in enumerate(placeholders):
        out = out.replace(f"\x00{index}\x00", value)
    return out


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def markdown(source: str, heading_offset: int = 0) -> str:
    """Render the markdown subset this project's documents actually use."""
    lines = source.splitlines()
    out: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]

        if line.startswith("```"):
            language = line[3:].strip()
            body: list[str] = []
            index += 1
            while index < len(lines) and not lines[index].startswith("```"):
                body.append(lines[index])
                index += 1
            index += 1
            klass = f' class="lang-{html.escape(language)}"' if language else ""
            out.append(
                f"<pre{klass}><code>"
                + html.escape("\n".join(body), quote=False)
                + "</code></pre>"
            )
            continue

        if line.startswith("#"):
            level = len(line) - len(line.lstrip("#"))
            text = line[level:].strip()
            level = min(level + heading_offset, 6)
            anchor = slug(text)
            out.append(
                f'<h{level} id="{anchor}">{inline(text)}'
                f'<a class="anchor" href="#{anchor}">#</a></h{level}>'
            )
            index += 1
            continue

        if line.lstrip().startswith("|") and index + 1 < len(lines) and re.fullmatch(
            r"\s*\|[\s:|-]+\|\s*", lines[index + 1]
        ):
            header = [c.strip() for c in line.strip().strip("|").split("|")]
            index += 2
            rows: list[list[str]] = []
            while index < len(lines) and lines[index].lstrip().startswith("|"):
                rows.append([c.strip() for c in lines[index].strip().strip("|").split("|")])
                index += 1
            head = "".join(f"<th>{inline(c)}</th>" for c in header)
            body = "".join(
                "<tr>" + "".join(f"<td>{inline(c)}</td>" for c in row) + "</tr>"
                for row in rows
            )
            out.append(f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>")
            continue

        bullet = re.match(r"\s*([-*]|\d+\.)\s+", line)
        if bullet:
            ordered = bullet.group(1).endswith(".")
            items: list[str] = []
            while index < len(lines):
                match = re.match(r"\s*(?:[-*]|\d+\.)\s+(.*)", lines[index])
                if not match:
                    if lines[index].startswith(("  ", "\t")) and items:
                        items[-1] += " " + lines[index].strip()
                        index += 1
                        continue
                    break
                items.append(match.group(1))
                index += 1
            tag = "ol" if ordered else "ul"
            out.append(
                f"<{tag}>" + "".join(f"<li>{inline(i)}</li>" for i in items) + f"</{tag}>"
            )
            continue

        if line.startswith(">"):
            quote: list[str] = []
            while index < len(lines) and lines[index].startswith(">"):
                quote.append(lines[index].lstrip(">").strip())
                index += 1
            out.append(f"<blockquote>{inline(' '.join(quote))}</blockquote>")
            continue

        if not line.strip():
            index += 1
            continue

        paragraph: list[str] = []
        while (
            index < len(lines)
            and lines[index].strip()
            and not lines[index].startswith(("#", "```", ">", "|"))
            and not re.match(r"\s*(?:[-*]|\d+\.)\s+", lines[index])
        ):
            paragraph.append(lines[index].strip())
            index += 1
        out.append(f"<p>{inline(' '.join(paragraph))}</p>")
    return "\n".join(out)


# --------------------------------------------------------------------------
# numpydoc docstrings
# --------------------------------------------------------------------------

_SECTIONS = ("Parameters", "Returns", "Raises", "Yields", "Notes", "Examples",
             "Attributes", "See Also", "References", "Warnings")


def render_docstring(text: str) -> str:
    """Render a numpydoc docstring: prose, parameter lists, example blocks."""
    if not text:
        return ""
    lines = text.splitlines()
    blocks: list[tuple[str, list[str]]] = [("", [])]
    index = 0
    while index < len(lines):
        line = lines[index]
        if (
            line.strip() in _SECTIONS
            and index + 1 < len(lines)
            and set(lines[index + 1].strip()) == {"-"}
        ):
            blocks.append((line.strip(), []))
            index += 2
            continue
        blocks[-1][1].append(line)
        index += 1

    out: list[str] = []
    for title, body in blocks:
        content = "\n".join(body).strip("\n")
        if not content.strip():
            continue
        if title in {"Examples", "Notes", "References", "See Also", "Warnings"}:
            out.append(f'<p class="doc-section">{title}</p>')
            if title == "Examples":
                out.append(f"<pre><code>{html.escape(content, quote=False)}</code></pre>")
            else:
                out.append(markdown(inspect.cleandoc(content), heading_offset=3))
            continue
        if title in {"Parameters", "Returns", "Raises", "Yields", "Attributes"}:
            out.append(f'<p class="doc-section">{title}</p><dl class="params">')
            name: str | None = None
            description: list[str] = []
            for raw in content.splitlines():
                if raw.strip() and not raw.startswith((" ", "\t")):
                    if name is not None:
                        out.append(
                            f"<dt>{inline(name)}</dt><dd>{inline(' '.join(description))}</dd>"
                        )
                    name, description = raw.strip(), []
                elif raw.strip():
                    description.append(raw.strip())
            if name is not None:
                out.append(f"<dt>{inline(name)}</dt><dd>{inline(' '.join(description))}</dd>")
            out.append("</dl>")
            continue
        out.append(markdown(content, heading_offset=3))
    return "\n".join(out)


# --------------------------------------------------------------------------
# API model
# --------------------------------------------------------------------------

GROUPS: list[tuple[str, str, list[str]]] = [
    ("Corpus", "Load a bibliographic export and normalise its keyword fields.",
     ["load_csv", "from_dataframe", "Corpus"]),
    ("Configuration", "Every threshold, weight and seed of a run lives here.",
     ["RunConfig", "GapConfig", "ClusteringConfig", "EncoderConfig",
      "EmergingWeights", "CombinationWeights", "CrossClusterWeights"]),
    ("Embedding backends", "Interchangeable encoders, from offline TF-IDF to hosted models.",
     ["available_encoders", "get_encoder", "register_encoder", "Encoder"]),
    ("Pipelines", "The two mining modes and the object they return.",
     ["run", "keywords_first", "articles_first", "PipelineResult"]),
    ("Detectors and scoring", "The four detectors, their scores, and the candidate type.",
     ["detect_emerging_concepts", "detect_conceptual_combinations",
      "detect_cross_cluster_concepts", "detect_peripheral_keywords",
      "score_emerging", "score_combination", "score_cross_cluster",
      "Gap", "GAP_TYPES", "gaps_to_frame", "deduplicate_gaps"]),
    ("Stability-aware consensus", "Repeat a mode across seeds and corpus sizes, pool by support.",
     ["consensus_gaps", "ConsensusResult", "DEFAULT_SEEDS", "jaccard"]),
    ("External rankings", "Assess a candidate list produced outside this package.",
     ["load_external_ranking", "EXTERNAL_GAP_TYPE"]),
    ("Keyword space and clustering", "Embedding, k-selection and cluster diagnostics.",
     ["build_keyword_space", "KeywordSpace", "select_k", "fit_kmeans",
      "rank_by_similarity", "centroid_similarity_matrix",
      "ClusterAssignment", "KSelectionResult"]),
    ("Text utilities", "Keyword normalisation, filters and salience.",
     ["normalize_keyword", "is_methodological_term", "keyword_frequencies",
      "core_domain_terms", "compute_tfidf_salience"]),
]

VALIDATION_GROUP = (
    "Assessment",
    "Annotation panel, agreement coefficients, control sets and expert sheets. "
    "Importable from <code>embedresearchgaps.validation</code>.",
    ["validate_gaps", "ValidationReport", "selected_and_control_keywords",
     "selected_and_all_keywords", "compare_keyword_sets", "SetComparison",
     "expert_llm_concordance", "permutation_mean_difference",
     "label_rates", "mean_novelty", "per_keyword_consensus",
     "fleiss_kappa", "krippendorff_alpha_ordinal", "pairwise_agreement",
     "annotations_to_frame", "build_expert_sheet", "write_expert_sheet",
     "load_expert_sheet", "expert_report",
     "available_providers", "get_annotator", "ChatAnnotator", "CallableAnnotator",
     "Annotation", "LABELS", "build_prompt"],
)


def signature_of(obj: object) -> str:
    try:
        return str(inspect.signature(obj))  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return ""


def render_entry(module: str, name: str, obj: object) -> str:
    anchor = slug(f"{module}-{name}")
    doc = inspect.getdoc(obj) or ""
    if inspect.isclass(obj):
        kind = "class"
    elif inspect.isfunction(obj) or inspect.isbuiltin(obj):
        kind = "function"
    else:
        kind = "constant"

    parts = [f'<section class="entry" id="{anchor}">']
    signature = html.escape(signature_of(obj), quote=False) if kind != "constant" else ""
    parts.append(
        f'<h3><span class="kind">{kind}</span> <code class="sym">{name}</code>'
        f'<code class="sig">{signature}</code>'
        f'<a class="anchor" href="#{anchor}">#</a></h3>'
    )
    if kind == "constant":
        parts.append(f"<pre><code>{html.escape(repr(obj)[:600], quote=False)}</code></pre>")
    parts.append(render_docstring(doc))

    fields = getattr(obj, "__dataclass_fields__", None) if inspect.isclass(obj) else None
    if fields:
        rows = []
        for field in fields.values():
            default = (
                "" if field.default is dataclasses.MISSING
                else html.escape(repr(field.default), quote=False)
            )
            if not default and field.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
                default = "<em>factory</em>"
            rows.append(
                f"<tr><td><code>{html.escape(field.name)}</code></td>"
                f"<td><code>{html.escape(str(field.type), quote=False)}</code></td>"
                f"<td><code>{default}</code></td></tr>"
            )
        parts.append(
            '<p class="doc-section">Fields</p><table class="fields"><thead><tr>'
            "<th>Name</th><th>Type</th><th>Default</th></tr></thead><tbody>"
            + "".join(rows)
            + "</tbody></table>"
        )

    if inspect.isclass(obj):
        methods = []
        for mname, member in inspect.getmembers(obj):
            if mname.startswith("_"):
                continue
            if isinstance(member, property):
                methods.append((mname, "", inspect.getdoc(member.fget) or ""))
            elif inspect.isfunction(member):
                methods.append((mname, signature_of(member), inspect.getdoc(member) or ""))
        if methods:
            parts.append('<p class="doc-section">Methods</p><dl class="methods">')
            for mname, msig, mdoc in methods:
                summary = mdoc.strip().splitlines()[0] if mdoc.strip() else ""
                parts.append(
                    f"<dt><code>{html.escape(mname)}"
                    f"{html.escape(msig, quote=False)}</code></dt>"
                    f"<dd>{inline(summary)}</dd>"
                )
            parts.append("</dl>")
    parts.append("</section>")
    return "\n".join(parts)


PAGES = [
    ("index.html", "Overview"),
    ("guide.html", "Guide"),
    ("api.html", "API reference"),
    ("changelog.html", "Changelog"),
]


def shell(title: str, active: str, body: str, subtitle: str = "", toc: str = "") -> str:
    nav = "".join(
        '<a href="{href}"{cls}>{label}</a>'.format(
            href=href, label=label, cls=' class="active"' if href == active else ""
        )
        for href, label in PAGES
    )
    aside = f'<aside class="toc"><p>On this page</p>{toc}</aside>' if toc else ""
    lede = f'<p class="lede">{subtitle}</p>' if subtitle else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)} · EmbedResearchGaps</title>
<meta name="description" content="EmbedResearchGaps: embedding-driven identification of candidate research gaps in author-keyword space.">
<link rel="stylesheet" href="style.css">
</head>
<body>
<header>
  <div class="bar">
    <a class="brand" href="index.html">EmbedResearchGaps</a>
    <nav>{nav}</nav>
    <a class="gh" href="{REPO_URL}">GitHub</a>
  </div>
</header>
<main>
  <div class="page">
    <h1>{html.escape(title)}</h1>
    {lede}
    {body}
  </div>
  {aside}
</main>
<footer>
  <p>EmbedResearchGaps · MIT licence ·
     <a href="{REPO_URL}">source</a> ·
     generated from the package by <code>tools/build_docs.py</code></p>
</footer>
</body>
</html>
"""


CSS = """
:root{--ink:#17202a;--muted:#5b6b7c;--line:#e2e8ee;--bg:#ffffff;--soft:#f6f8fa;
      --accent:#1f5fa8;--code:#0b3d66;--kind:#8a6d1f}
*{box-sizing:border-box}
html{scroll-behavior:smooth}
body{margin:0;background:var(--bg);color:var(--ink);
     font:16px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
     -webkit-font-smoothing:antialiased}
header{border-bottom:1px solid var(--line);position:sticky;top:0;background:rgba(255,255,255,.94);
       backdrop-filter:blur(6px);z-index:5}
.bar{max-width:1180px;margin:0 auto;padding:.7rem 1.2rem;display:flex;align-items:center;gap:1.4rem}
.brand{font-weight:650;color:var(--ink);text-decoration:none;letter-spacing:-.01em}
header nav{display:flex;gap:1.1rem;flex:1}
header nav a{color:var(--muted);text-decoration:none;font-size:.93rem;padding:.15rem 0;
             border-bottom:2px solid transparent}
header nav a:hover{color:var(--ink)}
header nav a.active{color:var(--accent);border-bottom-color:var(--accent)}
.gh{color:var(--muted);text-decoration:none;font-size:.9rem}
.gh:hover{color:var(--ink)}
main{max-width:1180px;margin:0 auto;padding:2.2rem 1.2rem 3rem;display:flex;gap:2.4rem;
     align-items:flex-start}
.page{flex:1;min-width:0;max-width:52rem}
h1{font-size:2rem;line-height:1.2;letter-spacing:-.02em;margin:0 0 .6rem}
h2{font-size:1.35rem;letter-spacing:-.01em;margin:2.4rem 0 .7rem;padding-top:.3rem}
h3{font-size:1.06rem;margin:1.8rem 0 .5rem}
h4{font-size:.98rem;margin:1.3rem 0 .4rem}
.lede{font-size:1.09rem;color:var(--muted);margin:0 0 1.6rem}
p{margin:.75rem 0}
a{color:var(--accent)}
code{font:.885em/1.5 ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
     background:var(--soft);padding:.12em .36em;border-radius:4px;color:var(--code)}
pre{background:var(--soft);border:1px solid var(--line);border-radius:8px;padding:.9rem 1rem;
    overflow:auto;margin:1rem 0}
pre code{background:none;padding:0;color:var(--ink);font-size:.85rem;line-height:1.6}
table{border-collapse:collapse;width:100%;margin:1.1rem 0;font-size:.93rem}
th,td{border:1px solid var(--line);padding:.46rem .7rem;text-align:left;vertical-align:top}
th{background:var(--soft);font-weight:600}
blockquote{margin:1.1rem 0;padding:.1rem 0 .1rem 1rem;border-left:3px solid var(--line);
           color:var(--muted)}
ul,ol{padding-left:1.3rem}
li{margin:.3rem 0}
.anchor{opacity:0;margin-left:.45rem;text-decoration:none;color:var(--muted);font-weight:400}
h1:hover .anchor,h2:hover .anchor,h3:hover .anchor{opacity:1}
.entry{border-top:1px solid var(--line);padding-top:.4rem;margin-top:1.8rem}
.entry h3{display:flex;flex-wrap:wrap;align-items:baseline;gap:.5rem;margin-top:.8rem}
.kind{font-size:.68rem;text-transform:uppercase;letter-spacing:.09em;color:var(--kind);
      border:1px solid var(--line);border-radius:4px;padding:.1rem .4rem;background:var(--soft)}
.sym{background:none;padding:0;font-size:1rem;font-weight:650;color:var(--ink)}
.sig{background:none;padding:0;color:var(--muted);font-weight:400;font-size:.85rem}
.doc-section{font-size:.74rem;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);
             margin:1.1rem 0 .3rem;font-weight:600}
dl.params,dl.methods{margin:.2rem 0 .6rem}
dl.params dt,dl.methods dt{font-weight:600;margin-top:.55rem;font-size:.93rem}
dl.params dd,dl.methods dd{margin:.1rem 0 0 1.1rem;color:var(--muted);font-size:.93rem}
table.fields{font-size:.88rem}
.toc{width:15rem;flex:none;position:sticky;top:4.2rem;font-size:.87rem;max-height:80vh;
     overflow:auto}
.toc p{font-size:.72rem;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);
       font-weight:600;margin:0 0 .5rem}
.toc a{display:block;color:var(--muted);text-decoration:none;padding:.17rem 0;line-height:1.35}
.toc a:hover{color:var(--accent)}
.toc a.sub{padding-left:.8rem;font-size:.84rem}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(15rem,1fr));gap:1rem;
       margin:1.5rem 0}
.card{border:1px solid var(--line);border-radius:9px;padding:1rem 1.1rem;background:var(--bg)}
.card h3{margin:.1rem 0 .35rem;font-size:1rem}
.card p{margin:0;color:var(--muted);font-size:.92rem}
.card a{text-decoration:none}
footer{border-top:1px solid var(--line);margin-top:2rem}
footer p{max-width:1180px;margin:0 auto;padding:1.2rem;color:var(--muted);font-size:.86rem}
@media (max-width:950px){.toc{display:none}main{padding-top:1.5rem}}
"""


def toc_from(entries: list[tuple[str, str, bool]]) -> str:
    return "".join(
        '<a class="{cls}" href="#{anchor}">{label}</a>'.format(
            cls="sub" if sub else "", anchor=anchor, label=html.escape(label)
        )
        for anchor, label, sub in entries
    )


def build() -> list[Path]:
    import embedresearchgaps as pkg
    from embedresearchgaps import validation as val

    OUT.mkdir(exist_ok=True)
    written: list[Path] = []

    # ---- API reference -------------------------------------------------
    sections: list[str] = []
    toc: list[tuple[str, str, bool]] = []
    groups: list[tuple[str, str, list[str], object]] = [
        (title, description, names, pkg) for title, description, names in GROUPS
    ]
    groups.append((VALIDATION_GROUP[0], VALIDATION_GROUP[1], VALIDATION_GROUP[2], val))
    total = 0
    for title, description, names, container in groups:
        anchor = slug(title)
        toc.append((anchor, title, False))
        sections.append(
            f'<h2 id="{anchor}">{html.escape(title)}<a class="anchor" href="#{anchor}">#</a></h2>'
        )
        sections.append(f"<p>{description}</p>")
        module = "embedresearchgaps.validation" if container is val else "embedresearchgaps"
        for name in names:
            obj = getattr(container, name, None)
            if obj is None:
                continue
            total += 1
            toc.append((slug(f"{module}-{name}"), name, True))
            sections.append(render_entry(module, name, obj))
    (OUT / "api.html").write_text(
        shell("API reference", "api.html", "\n".join(sections),
              subtitle=f"{total} public objects, generated from the installed package "
                       f"(version {pkg.__version__}).",
              toc=toc_from(toc)),
        encoding="utf-8",
    )
    written.append(OUT / "api.html")

    # ---- Guide, from the README ---------------------------------------
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    body = readme.split("\n", 1)[1] if readme.startswith("# ") else readme
    guide_toc = [
        (slug(match.group(1)), match.group(1), match.group(0).startswith("###"))
        for match in re.finditer(r"^(?:##|###) (.+)$", body, re.M)
    ]
    (OUT / "guide.html").write_text(
        shell("Guide", "guide.html", markdown(body),
              subtitle="Installation, input formats, the two modes, filters, backends and "
                       "reproducibility, rendered from the repository README.",
              toc=toc_from(guide_toc)),
        encoding="utf-8",
    )
    written.append(OUT / "guide.html")

    # ---- Changelog -----------------------------------------------------
    changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    body = changelog.split("\n", 1)[1] if changelog.startswith("# ") else changelog
    (OUT / "changelog.html").write_text(
        shell("Changelog", "changelog.html", markdown(body)), encoding="utf-8"
    )
    written.append(OUT / "changelog.html")

    # ---- Landing page --------------------------------------------------
    def summarise(module_name: str) -> tuple[str, str]:
        module = importlib.import_module(module_name)
        doc = (inspect.getdoc(module) or "").strip().splitlines()
        return module_name.rsplit(".", 1)[-1], doc[0] if doc else ""

    modules = [summarise(f"embedresearchgaps.{n}") for n in
               ["config", "corpus", "text", "keywords", "clustering", "encoders", "gaps",
                "external", "pipelines", "consensus", "results", "viz", "cli"]]
    validation_modules = [summarise(f"embedresearchgaps.validation.{n}") for n in
                          ["annotators", "protocol", "runner", "metrics", "experts"]]

    def module_table(rows: list[tuple[str, str]], prefix: str) -> str:
        return (
            "<table><thead><tr><th>Module</th><th>Purpose</th></tr></thead><tbody>"
            + "".join(
                f"<tr><td><code>{prefix}{name}</code></td><td>{inline(summary)}</td></tr>"
                for name, summary in rows
            )
            + "</tbody></table>"
        )

    intro = f"""
<p>EmbedResearchGaps turns the author-keyword space of a screened corpus into a short,
typed, source-linked list of candidate research gaps, and measures how reproducible that
list is. Formulating a gap stays a creative act; what the package contributes is a
shortlist stripped of trivial and already-covered terms, with its stability reported
rather than assumed.</p>

<div class="cards">
  <div class="card"><h3><a href="guide.html">Guide</a></h3>
    <p>Install it, point it at a CSV export, run either mode, read the candidate table.</p></div>
  <div class="card"><h3><a href="api.html">API reference</a></h3>
    <p>Every public object, with signatures and docstrings read from the package itself.</p></div>
  <div class="card"><h3><a href="{REPO_URL}">Source</a></h3>
    <p>Repository, test suite and the deposited runs behind the published study.</p></div>
</div>

<h2 id="install">Install<a class="anchor" href="#install">#</a></h2>
<pre><code>git clone {REPO_URL}.git
cd EmbedResearchGaps
pip install -e .</code></pre>

<h2 id="quick-start">Quick start<a class="anchor" href="#quick-start">#</a></h2>
<pre><code>from embedresearchgaps import load_csv, RunConfig, articles_first

corpus = load_csv("scopus.csv")
result = articles_first(corpus, RunConfig(top_n_articles=50))

print(result.gaps[["gap_type", "keyword", "score", "rationale"]].head())
result.save("results")</code></pre>
<p>Or from the shell:</p>
<pre><code>embedresearchgaps run scopus.csv --mode articles_first --top-n 50 --figures</code></pre>

<h2 id="the-two-modes">The two modes<a class="anchor" href="#the-two-modes">#</a></h2>
<table><thead><tr><th>Mode</th><th>What it clusters</th><th>What it flags</th></tr></thead>
<tbody>
<tr><td><code>keywords_first</code></td><td>the unique author keywords</td>
    <td>keywords whose distance from their own cluster centroid exceeds a
        cluster-specific percentile</td></tr>
<tr><td><code>articles_first</code></td><td>the articles</td>
    <td>emerging concepts, unrealised combinations and cross-cluster concepts inside each
        cluster's keyword sub-space</td></tr>
</tbody></table>
<p>Both return a <code>PipelineResult</code>: a candidate table with scores, metrics,
rationales and source records, plus the diagnostics a methods section needs. A ranking
produced by another tool enters the same object through
<a href="api.html#embedresearchgaps-load-external-ranking"><code>load_external_ranking</code></a>,
so the assessment layer applies to it unchanged.</p>

<h2 id="module-map">Module map<a class="anchor" href="#module-map">#</a></h2>
{module_table(modules, "embedresearchgaps.")}
<p>The assessment subpackage:</p>
{module_table(validation_modules, "embedresearchgaps.validation.")}

<h2 id="citing">Citing<a class="anchor" href="#citing">#</a></h2>
<p>Citation metadata is in
<a href="{REPO_URL}/blob/main/CITATION.cff"><code>CITATION.cff</code></a>.</p>
"""
    (OUT / "index.html").write_text(
        shell("EmbedResearchGaps", "index.html", intro,
              subtitle="Embedding-driven identification of candidate research gaps in "
                       "author-keyword space.",
              toc=toc_from([("install", "Install", False),
                            ("quick-start", "Quick start", False),
                            ("the-two-modes", "The two modes", False),
                            ("module-map", "Module map", False),
                            ("citing", "Citing", False)])),
        encoding="utf-8",
    )
    written.append(OUT / "index.html")

    (OUT / "style.css").write_text(CSS.strip() + "\n", encoding="utf-8")
    written.append(OUT / "style.css")
    (OUT / ".nojekyll").write_text("", encoding="utf-8")
    written.append(OUT / ".nojekyll")
    return written


if __name__ == "__main__":
    for path in build():
        print(path.relative_to(ROOT), path.stat().st_size)
